### ISSUE TITLE
Strong Password Program(Hackerrank)

### ISSUE THREAD

**Issue by UG-SEP** [kothariji/competitive-programming#250]
Hey,
I wanted to add [strong password](https://www.hackerrank.com/challenges/strong-password/problem) (Hackerrank Question)

Statement: To find the minimum change to create a password strong

Strong Password criteria:
* Its length is at least .
* It contains at least one digit.
* It contains at least one lowercase English character.
* It contains at least one uppercase English character.
* It contains at least one special character. The special characters are: !@#$%^&*()-+
`Example:`
`Input:`  enter password size: 3  Password: Ab1
`Output:` 3 change need to create the password as strong password
 please assign me 
thanks

**Comment by kothariji** [comment]
Hi @UG-SEP , First of all, thank you so much for taking out the time to create this issue.

Definitely 🙌, Please go forward. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥
