### ISSUE TITLE
Prim's algorithm

### ISSUE THREAD

**Issue by UG-SEP** [kothariji/competitive-programming#255]
Hey,
 I wanted to add Prim's algorithm 
It is a way to find Minimal spanning tree(Minimum cost to traverse all node)
I wanted to add it [here](https://github.com/kothariji/competitive-programming/tree/master/Graph)
Please assign it to me 
Thanks

**Comment by kothariji** [comment]
Hi @UG-SEP , First of all, thank you so much for taking out the time to create this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥
