### ISSUE TITLE
Edit README.md formatting.

### ISSUE THREAD

**Issue by shivanshu-semwal** [kothariji/competitive-programming#259]
![image](https://user-images.githubusercontent.com/53912074/119362713-9ee2a000-bcca-11eb-8a99-4eada21fdacf.png)

Just a suggestion, remove these big link by just `[video](url)` or blog/article url with `[article](url)`. I can send a pr, just let me know.

**Comment by kothariji** [comment]
Hi @shivanshu-semwal, First of all, thank you so much for taking out the time to create this issue.

Yes sure, please go-ahead to work on this issue. I am assigning it to you. 🚀 

And last but not least,
Keep Contributing 🙏🔥
