### ISSUE TITLE
Tic Tac Toe AI Integrated (Under Hacktoberfeast)

### ISSUE THREAD

**Issue by UG-SEP** [kothariji/competitive-programming#269]
Hey @kothariji
Wanted to add a Tic Tac Toe game❌-⭕
[View Project](https://github.com/UG-SEP/Tic-Tac-Toe-AI-Intergrated)

**Comment by kothariji** [comment]
Woah 🔥  This looks amazing, Please go forward 🙌

**Comment by UG-SEP** [comment]
@kothariji
 Is your project under Hacktoberfeast2021?
