### ISSUE TITLE
I want to add Cryptographic Algos and many more

### ISSUE THREAD

**Issue by prabaljainn** [kothariji/competitive-programming#314]
Please assign this task to me

**Comment by kothariji** [comment]
Done 🚀

**Comment by prabaljainn** [comment]
@kothariji please add @hacktoberfest tag

**Comment by kothariji** [comment]
done 🚀

**Comment by prabaljainn** [comment]
should i add something else?

**Comment by kothariji** [comment]
No, if you have added the algo, you can close this issue 🤝 
Thanks 😇
