### ISSUE TITLE
Add Codechef Snackdown Problems

### ISSUE THREAD

**Issue by JahnaviKashyap19** [kothariji/competitive-programming#426]
Can I add the SnackDown problems of codechef?

**Comment by kothariji** [comment]
Old SnackDown problem solutions right?

**Comment by JahnaviKashyap19** [comment]
yes

**Comment by kothariji** [comment]
Sure you can add those in A directory named SnackDown_YEAR in Codechf Solutions Folder

**Comment by JahnaviKashyap19** [comment]
Okay thanks. Could you add the label hacktoberfest?

**Comment by prehans** [comment]
Can I add codechef snackdown problem?
