### ISSUE TITLE
Similar File names causing issue

### ISSUE THREAD

**Issue by iamscoobydoo** [kothariji/competitive-programming#516]
There are two files under the folder `Leetcode - Top Interview Questions` which have similar names - 3sum.cpp and 3Sum.cpp. 
This is causing only one of those two files to be cloned to local. 
Here is the warning screenshot when cloning the repository.
![Capture](https://user-images.githubusercontent.com/73542054/137200833-715c1b67-77f7-444a-ad57-75d48e4a3749.PNG)
Also, the file is marked as `modified` by Git.

**Comment by kothariji** [comment]
Oh thanks for letting me know
We can go forward and remove 1 file

if you wish to work on this issue, please let me know
